# Generated by Django 5.2.15 on 2026-06-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('PROFESSIONAL', 'Expérience professionnelle'), ('CONSULTING', 'Mission de conseil'), ('ACADEMIC', 'Projet académique'), ('PERSONAL', 'Projet personnel')], default='PERSONAL', max_length=20),
        ),
    ]
