# Generated by Django 5.2.15 on 2026-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_align_parcours_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text="Rétrospective d'ingénierie — difficultés réelles, surprises, compromis effectués, ce que je referais différemment. Pas de vérités génériques."),
        ),
    ]
